### ISSUE TITLE
Üye ol butonu yapılacak

### ISSUE THREAD

**Issue by Gencaver1** [ProgrammingApp/ProgrammingApp#1]
Üye ol butonu yapılacak javada

**Comment by hur-general** [comment]
Hi brothers

**Comment by hur-general** [comment]
Eyvallah cengaver

9 Nis 2018 20:20 tarihinde "Gencaver1" <notifications@github.com> yazdı:

hi

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/ProgrammingApp/ProgrammingApp/issues/1#issuecomment-379827909>,
or mute the thread
